### ISSUE TITLE
Tag 1.0.0

### ISSUE THREAD

**Issue by scottrobertson** [scottrobertson/fintech-to-ynab#10]
@rossdargan how do you feel about this? We ready to tag a "stable" release?

**Comment by rossdargan** [comment]
Lets give it a few weeks to bed in. I'd like to push a few more transactions through it before the big 1.0! Feature wise it's totally there though.

**Comment by rossdargan** [comment]
I had to restart my docker image to get a transaction in this morning. The log isn't that helpful:

DEBUG:settings:webhook type received transaction.created
DEBUG:settings:syncing
DEBUG:pynYNAB.Client:Client.sync
DEBUG:pynYNAB.connection:syncCatalogData  ... {'request_data': '{"user_id": "f60d1795-3c35-4c28-bbd0-3c4af9e62fe8", "changed_entities": {}, "device_knowledge_of_server": 521398338, "ending_device_knowledge": 2, "starting_device_knowledge": 2}', u'operation_name': 'syncCatalogData'}
DEBUG:requests.packages.urllib3.connectionpool:Resetting dropped connection: app.youneedabudget.com
DEBUG:requests.packages.urllib3.connectionpool:https://app.youneedabudget.com:443 "POST /api/v1/catalog HTTP/1.1" 200 None
DEBUG:pynYNAB.ObjClient:server_knowledge_of_device 2
DEBUG:pynYNAB.ObjClient:current_server_knowledge 522513344
DEBUG:pynYNAB.ObjClient:Server knowledge has gone up by 1115006. We should be getting back some entities from the server
DEBUG:pynYNAB.ObjClient:current_device_knowledge 2
DEBUG:pynYNAB.ObjClient:device_knowledge_of_server 522513344
DEBUG:pynYNAB.connection:syncBudgetData  ... {'request_data': '{"budget_version_id": "8ab7902c-bb25-46f9-94fd-676406987be1", "changed_entities": {}, "device_knowledge_of_server": 27257, "ending_device_knowledge": 2, "starting_device_knowledge": 2, "calculated_entities_included": false}', u'operation_name': 'syncBudgetData'}
DEBUG:requests.packages.urllib3.connectionpool:https://app.youneedabudget.com:443 "POST /api/v1/catalog HTTP/1.1" 200 None
DEBUG:pynYNAB.ObjClient:server_knowledge_of_device 2
DEBUG:pynYNAB.ObjClient:current_server_knowledge 27276


My feeling is we need to test this running for at least a couple of weeks in a stable format to prove that having the client remain in memory doesn't cause issues.

**Comment by scottrobertson** [comment]
Tagged v0.1 before merging in the PR from @jslvtr
