### ISSUE TITLE
Worth adding some sort of secret URL part

### ISSUE THREAD

**Issue by rossdargan** [scottrobertson/fintech-to-ynab#18]
I'm worried it will become really easy to scan for this web hook. It might be worth configuring the URL we listen too to include a configurable pretty shared secret. 

Until ynab add a way to sign or encrypt the payload this might be the best we can do.

**Comment by scottrobertson** [comment]
Agreed. Just a simple query param would be fine

**Comment by scottrobertson** [comment]
I will get this done 👍

**Comment by scottrobertson** [comment]
I have added this. We just needs some docs around it now

**Comment by rossdargan** [comment]
Ha ha you don't hang about do you. Feel guilty just adding it! Nice work though!

**Comment by rossdargan** [comment]
I've confirmed this now works fine, and the docs you have added cover it's use just fine (https://github.com/scottrobertson/fintech-to-ynab/wiki/Getting-Started#url-secret)
