### ISSUE TITLE
Handle YNAB failure + Duplicate transaction case

### ISSUE THREAD

**Issue by scottrobertson** [scottrobertson/fintech-to-ynab#19]
The following just happened:

- Webhook came in
- YNAB raised Rate Limit error*
- Monzo sent the webhook again
- We returned "duplicate"

This happened because we pushed the transaction into be_transactions, but then didnt end up syncing it with YNAB. Not sure what the best course of action is here.

*it's low at the moment as they have a huge bug in the mobile apps that were killing the DB.

**Comment by rienafairefr** [comment]
Is this something that I can fix on my side ? I guess YNAB sent us a request_throttled error, then the library retries after the delay that the server sent, more or less indefinitely

**Comment by scottrobertson** [comment]
@rienafairefr i am not sure. Based on my understanding, the following would happen right now:

 - We receive the webhook
 - Adds to be_transactions
 - Sync fails
 - Webhook retires
 - Duplicate

But then:

 - Another transaction comes in
 - Sync happens
 - Both transactions are synced

The issue arises when a deployment happens between the 2 transactions as the be_transactions will be reset, and transaction 1 will be lost.

I feel like the cleanest solution for our side is to remove the transaction from be_transactions when the sync fails.

**Comment by rossdargan** [comment]
It looks like this is not the same issue as #26, however the failure results in the duplicate.

I think after a failure we need to kill the local copy of the ynab service somehow... if we could somehow re-load it in the background we would be golden...

What does heroku do if the app service dies? If it restarts it then maybe it's best to let the app die in the short term?!
