### ISSUE TITLE
We need a new name

### ISSUE THREAD

**Issue by scottrobertson** [scottrobertson/fintech-to-ynab#22]
I am adding Starling support, so... we need a new name. Suggestions?

**Comment by Stephan5** [comment]
Hmmm... how about.. `starling-to-ynab` ? ;)

**Comment by scottrobertson** [comment]
:D

**Comment by ganey** [comment]
You're always one step ahead haha! I was going to start on that this week, got my Starling account today.

Maybe fintech-to-ynab or something? Finlink? I'm no good with names :(

**Comment by ganey** [comment]
Are you thinking separate repo or the same one handling Monzo and starling?

**Comment by scottrobertson** [comment]
We can just keep it all in 1. Most of the code can be shared (for actually pushing to YNAB). Formatting the webhooks from the various banks is pretty simple. 

The Starling support is actually already in and working, but getting webhooks working is a bit tricky (requires submitting a client for approval etc) but they have added [this](https://trello.com/b/wp8bOZPL/starling-developers-roadmap) to Trello to make it easier.

**Comment by ganey** [comment]
Ok sure was just checking. 

Ah thanks, I've been away so haven't been keeping up with what's going on. Which reminds me, I need to go catch up on what's going on with Tandem

**Comment by scottrobertson** [comment]
@rossdargan any ideas?

**Comment by rossdargan** [comment]
bloody hell, naming stuff is the hardest part :)

bank-to-ynab
bank it for ynab
web hook importer for ynab - whify

**Comment by Stephan5** [comment]
I like fintech-to-ynab the most 👍
