### ISSUE TITLE
Failed Monzo Transactions

### ISSUE THREAD

**Issue by ganey** [scottrobertson/fintech-to-ynab#27]
Today I accidentally tried to pay for something with my Monzo card, but didn't have enough balance, so caused a failed transaction, as expected.

It did however still fire a webhook, hit my Heroku box, create an entry in YNAB, and mark it as cleared.

I'll try and re-simulate one with more logging, although it may just be that I'm on an outdated copy of this repo as I haven't re-deployed for a few weeks.

**Comment by rossdargan** [comment]
to be honest one of the best things you can do is capture the webhook using https://requestb.in.

This way we can see what the call looks like.

Maybe we need an enhanced logging mode the spits out the data received from the webhook call as is?

**Comment by scottrobertson** [comment]
This seems like an issue on Monzo's end. They should not be firing `transaction.created` webhooks for failed transactions.

**Comment by rossdargan** [comment]
If this isn't temporary we can filter these transactions out via the property "include_in_spending" Managed to find one in my logs, but I can't tell if it got transaction.created. Possibly worth adding this filter anyway...
