### ISSUE TITLE
CI Failing

### ISSUE THREAD

**Issue by scottrobertson** [scottrobertson/fintech-to-ynab#30]
Hey @rienafairefr. After merging your branch, CI is failing

https://circleci.com/gh/scottrobertson/fintech-to-ynab/32

**Comment by rienafairefr** [comment]
ah, mybad, I had added mock module for the tests, in my `requirements.txt` but it wasnt in the `testable `branch`

**Comment by scottrobertson** [comment]
No problem :) do you want to PR it in, or should i add it? If so, what am i adding?

**Comment by rienafairefr** [comment]
just sent a PR that adds it, should solve the issue

**Comment by scottrobertson** [comment]
@rienafairefr awesome thanks.

I fixed a couple of the tests (due to the new data dict) but a few in test_app are still failing.

**Comment by rienafairefr** [comment]
I see the problem. Send you a pr in a sec

**Comment by scottrobertson** [comment]
Last one:

```
======================================================================
FAIL: test_secret (tests.unit.test_app.TestRoutes)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ubuntu/fintech-to-ynab/tests/unit/test_app.py", line 17, in test_secret
    self.assertEqual(response.status_code,403)
AssertionError: 400 != 403
```

**Comment by rienafairefr** [comment]
I think it's the URL_SECRET environment variable that doesnt exist in CI ?

**Comment by rienafairefr** [comment]
I can reproduce locally if I remove URL_SECRET=[...] from my .env
