### ISSUE TITLE
double init ?

### ISSUE THREAD

**Issue by rienafairefr** [scottrobertson/fintech-to-ynab#35]
ynab_client init() is called in the __main__ function, and also here anytime the webhook is called,

https://github.com/scottrobertson/fintech-to-ynab/blob/master/python/routes.py#L39

Either we init and for every webhook call (then the __main__ call is not needed), or we init only once when the app is created, in __main__ (then the call for each route is not needed)  ?

**Comment by scottrobertson** [comment]
It should just be calling sync on at the start of each webhook.
