### ISSUE TITLE
Remove auto category

### ISSUE THREAD

**Issue by scottrobertson** [scottrobertson/fintech-to-ynab#36]
Now that YNAB have payee management with auto categorising, i think we can get rid of all our logic:

http://docs.youneedabudget.com/article/611-payee-management

**Comment by rienafairefr** [comment]
It depends how they do it in the web app. If the logic is on the client then send payee/categories to the api, then we still need to do the logic. But we might have some luck (like, push a transaction with a given payee, and get a return with an automatic category), but I wouldnt bet on it :-/

**Comment by scottrobertson** [comment]
I suspect it needs to be server side as if it didn't work with auto
imports, people would be annoyed. Will test.

On 20 Jul 2017 03:35, "rienafairefr" <notifications@github.com> wrote:

It depends how they do it in the web app. If the logic is on the client
then send payee/categories to the api, then we still need to do the logic.
But we might have some luck (like, push a transaction with a given payee,
and get a return with an automatic category), but I wouldnt bet on it :-/

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/scottrobertson/fintech-to-ynab/issues/36#issuecomment-316665005>,
or mute the thread

**Comment by scottrobertson** [comment]
This can now be removed once YNAB support this in the new API. This should be done by next week.

**Comment by rienafairefr** [comment]
This issue notified me about some changes and the YNAB API is live, I hadnt seen it before. I see they provide a swagger spec, it's super great, that'll permit generation of a client library in Python in a matter of days :-) 👍

**Comment by scottrobertson** [comment]
Yeah it's pretty great. Private beta for now, but it should be available to everyone soon :)

**Comment by scottrobertson** [comment]
This is now handled by YNAB via the API.
