### ISSUE TITLE
License? Can "bank2ynab" grab code from you?

### ISSUE THREAD

**Issue by torbengb** [scottrobertson/fintech-to-ynab#41]
Hi Scott, and greetings from the `bank2ynab` project. I've seen that you have a way to push transactions directly into YNAB, and it would be neat if we could incorporate that into our project, too. But I don't see a license in your project, so I am asking you explicitly for permission. (Also, maybe you should add a license?)

Kind regards from Austria!
 - Ben

**Comment by scottrobertson** [comment]
Hey @torbengb. You will need to ask over at https://github.com/rienafairefr/pynYNAB 👍
