### ISSUE TITLE
Transaction changes not applied in YNAB

### ISSUE THREAD

**Issue by cawilliamson** [scottrobertson/fintech-to-ynab#44]
I'm not sure if this is something you can actually fix at your end but when I pay at the pump for fuel the price is always £1 for a day or so and then the transaction is adjusted to the actual amount.

This is not reflected in YNAB sadly since it doesn't seem to create another transaction so YNAB only shows £1 instead of £45 which the transaction actually was.

**Comment by scottrobertson** [comment]
Part of the problem is that Monzo do not send any sort of notification for updated transactions.

**Comment by ganey** [comment]
Is 'update webhooks' already raised with Monzo?

There can also be small differences in price when paying in a different
currency. AWS charge me in USD which by the time it clears in Monzo the
amount can change by a few pence.

**Comment by scottrobertson** [comment]
They are not really making any changes to the API just now. They already plan to add it though.
