### ISSUE TITLE
YNAB API Rewrite

### ISSUE THREAD

**Issue by scottrobertson** [scottrobertson/fintech-to-ynab#45]
> As part of the YNAB API release, I will be rewriting this library. In the process, i will be switching away from Python to using Ruby. The only reason it was in Python before was due to the nynab-api library being written in Python. I don't know much Python, so it's been a bit of a pain to maintain this. V1 will stay available for anyone who wants to continue to use the Python version.

I have created a project for this https://github.com/scottrobertson/fintech-to-ynab/projects/1

This ticket will be left open for discussions.

**Comment by ganey** [comment]
Any reason you haven't gone for the JS library, or are you more comfortable with Ruby? https://api.youneedabudget.com/#client-javascript

**Comment by scottrobertson** [comment]
@ganey purely just more comfortable with Ruby as it's what i work with every day.

**Comment by scottrobertson** [comment]
Closing in favour of #49
