### ISSUE TITLE
Memory usage

### ISSUE THREAD

**Issue by scottrobertson** [scottrobertson/fintech-to-ynab#5]
Just hit a "Memory quota exceeded" error on heroku. The app is using 592M of ram. That seems a bit excessive. Need to work out where this is happening, and if it's in our app, or in the library.

**Comment by ganey** [comment]
Are you using a free Heroku deploy?

I haven't updated my instance for a few weeks so I don't have any of the latest changes between you and Ross.

Also wondering if I should wait for [Pull 6](https://github.com/scottrobertson/monzo-to-ynab/pull/6) before redeploying.

Thanks for all the work you guys are putting into this!

**Comment by scottrobertson** [comment]
I am using free heroku to test this out yeah. I would hold off on deploying just now until we work out the memory issue.

#6 has been merged already though :)

**Comment by scottrobertson** [comment]
@rienafairefr do you have any ideas on this? Do you think it will be in the library? I don't see anywhere in our code that will be causing a memory leak like this after only a few syncs.

**Comment by rossdargan** [comment]
FYI on docker it sits around 280mb for my dataset.

**Comment by scottrobertson** [comment]
How many transactions do you have?

**Comment by rossdargan** [comment]
device_knowledge_of_server 520396382

**Comment by rossdargan** [comment]
I'm going to update my docker image. I'm pretty happy with this release now on docker.

**Comment by scottrobertson** [comment]
I can get it setup on Dockerhub if you want so that it auto builds from master?

**Comment by rossdargan** [comment]
It's up to you. might make sense. I'll keep mine up to date, but point people to yours going forward.

**Comment by rienafairefr** [comment]
Depends. Is memory usage increasing with each sync or push? If there is a
boatload of user data /transactions, that could use ram for sure

**Comment by scottrobertson** [comment]
@rossdargan it's consistently using around 5/600. I have around 3000 transactions in YNAB. However, even 100mb for that many transactions seems insane. That would be about 30kb per transaction, which they are 100% not?

**Comment by scottrobertson** [comment]
@rienafairefr i will do some reading into Python profiling and see if i can work out where the memory usage is coming from

**Comment by rossdargan** [comment]
@scottrobertson Mines at 260mb now. Looks like profiling will be the way forward.

**Comment by scottrobertson** [comment]
I got rid of gunicorn, it's dropped to ~400mb from higher 500's. I will keep an eye on it.

**Comment by rienafairefr** [comment]
As a baseline, without any data in it a Client object gives around 30-40 MB memory usage, just tested. I've created an offline client and added 5000 transactions to it, memory usage goes up to only 55 MB. A test budget with around 800 total entities, only 40-50 MB. what's taking you to hundreds of MB, this is weird..

**Comment by scottrobertson** [comment]
Interesting. I dont know much python, so it's very likely that I am doing something stupid in my code :D

**Comment by rienafairefr** [comment]
Just so you know, in the most recent update 0.5.2 of the library I've added a possibility to do selective sync. Instead of using client.sync, you can do:

    client.sync(['be_payees'])

It's still a beta test maybe it doesnt work very well, but normally with that then the client only contains the payees without the overhead of all the user data. This might help for this issue, and maybe the other one where sync takes too much time 👍

**Comment by scottrobertson** [comment]
Oh nice :) 

I think we will still do the full sync though each time as we want the latest transactions so we can take the category from them to auto fill that.
